openapi: 3.0.3
info:
  title: Portfolio Site API
  version: 1.0.0
  description: API endpoints for interactive portfolio site functionality

servers:
  - url: https://portfolio-site.web.app/api
    description: Production Firebase Functions

paths:
  /profile:
    get:
      summary: Get portfolio owner profile
      operationId: getProfile
      responses:
        '200':
          description: Profile data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
        '500':
          description: Internal server error

  /projects:
    get:
      summary: Get all portfolio projects
      operationId: getProjects
      parameters:
        - name: category
          in: query
          description: Filter projects by category
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter projects by status
          required: false
          schema:
            type: string
            enum: [completed, ongoing, archived]
      responses:
        '200':
          description: Projects retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

  /projects/{id}:
    get:
      summary: Get specific project details
      operationId: getProject
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found

  /skills:
    get:
      summary: Get all skills
      operationId: getSkills
      parameters:
        - name: category
          in: query
          description: Filter skills by category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Skills retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'

  /chat:
    post:
      summary: Send message to portfolio chatbot
      operationId: sendChatMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - sessionId
              properties:
                message:
                  type: string
                  minLength: 1
                  maxLength: 2000
                sessionId:
                  type: string
                conversationId:
                  type: string
      responses:
        '200':
          description: Chat response generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  conversationId:
                    type: string
                  tokens:
                    type: number
        '400':
          description: Invalid request
        '429':
          description: Rate limit exceeded
        '500':
          description: AI service error

  /resume:
    get:
      summary: Get structured resume data
      operationId: getResumeData
      responses:
        '200':
          description: Resume data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeData'

components:
  schemas:
    Profile:
      type: object
      required:
        - id
        - name
        - title
        - summary
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 100
        title:
          type: string
          minLength: 1
          maxLength: 200
        summary:
          type: string
        location:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        socialLinks:
          type: array
          items:
            type: object
            properties:
              platform:
                type: string
              url:
                type: string
                format: uri
        skills:
          type: array
          items:
            type: string

    Project:
      type: object
      required:
        - id
        - title
        - description
        - technologies
      properties:
        id:
          type: string
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          minLength: 10
          maxLength: 500
        longDescription:
          type: string
        technologies:
          type: array
          items:
            type: string
          minItems: 1
        category:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        status:
          type: string
          enum: [completed, ongoing, archived]
        images:
          type: array
          items:
            type: string
            format: uri
        links:
          type: object
          properties:
            live:
              type: string
              format: uri
            repository:
              type: string
              format: uri
        highlights:
          type: array
          items:
            type: string
        role:
          type: string
        teamSize:
          type: number
          minimum: 1

    Skill:
      type: object
      required:
        - id
        - name
        - category
        - level
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
          enum: [technical, soft, language, tool, framework]
        level:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        years:
          type: number
          minimum: 0
        verified:
          type: boolean
        projects:
          type: array
          items:
            type: string
        description:
          type: string

    ResumeData:
      type: object
      properties:
        personalInfo:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            phone:
              type: string
            location:
              type: string
        summary:
          type: string
        workExperience:
          type: array
          items:
            type: object
            properties:
              company:
                type: string
              position:
                type: string
              startDate:
                type: string
                format: date
              endDate:
                type: string
                format: date
                nullable: true
              location:
                type: string
              description:
                type: string
              achievements:
                type: array
                items:
                  type: string
        education:
          type: array
          items:
            type: object
            properties:
              institution:
                type: string
              degree:
                type: string
              field:
                type: string
              startDate:
                type: string
                format: date
              endDate:
                type: string
                format: date
              gpa:
                type: number
                minimum: 0
                maximum: 4
        lastUpdated:
          type: string
          format: date-time